spring:
  profiles:
    active: local # prod
  datasource:
    # TODO: CQRS pattern
#    read:
#      url: jdbc:postgresql://readonly-db:5432/mydb
#      username: readonly_user
#      password: readonly_password
#    write:
#      url: jdbc:postgresql://master-db:5432/mydb
#      username: master_user
#      password: master_password

    url: jdbc:postgresql://localhost:5432/subsync
    username: asd
    password: 123
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.connection.isolation: 2 # TRANSACTION_READ_COMMITTED
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      password: 123
      username: default

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

application:
  security:
    jwt:
      secret-key: "123"
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    root: INFO
#  file:
#    name: application.log


stripe:
  api-key: "123"